services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: fs_boilerplate
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  django:
    build:
      context: ./fullstackapp  
    container_name: fullstackapp
    restart: always
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: fullstackapp.settings
      DATABASE_HOST: db
      DATABASE_NAME: fs_boilerplate
      DATABASE_USER: admin
      DATABASE_PASSWORD: fs_boilerplate
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  vue:
    build:
      context: ./vue   
    environment:
      VITE_BACKEND_URL: http://localhost:8000
    command: npm run dev -- --host 0.0.0.0
    container_name: vue_frontend
    restart: always
    depends_on:
      - django  
    ports:
      - "5173:5173"
    volumes:
      - ./vue/src:/app/src
      - ./vue/public:/app/public
      - ./vue/package.json:/app/package.json
      - ./vue/package-lock.json:/app/package-lock.json

volumes:
  node_modules:
  mysql_data:
